### ISSUE TITLE
New bootloader [HHZ20f]

### ISSUE THREAD

**Issue by adhirajsinghchauhan** [bitdomo/imgdata#1]
Could you check if the imgdata is same as HHZ12h?

Better yet, could you post a tutorial on XDA, outlining how to extract the imgdata from bootloader.img?

**Comment by bitdomo** [comment]
It is the same.
I dont have any method to extract the imgdata from bootloader.img

I always check the ota zip files, because it has all bootloader partitions
in separate images instead of one bootloader.img
2016.05.03. 11:35 ezt írta ("Adhiraj Singh Chauhan" <
notifications@github.com>):

Could you check if the imgdata is same as HHZ12h?

Better yet, could you post a tutorial on XDA, outlining how to extract the
imgdata from bootloader.img?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub
https://github.com/bitdomo/imgdata/issues/1

**Comment by adhirajsinghchauhan** [comment]
Okay, thanks a lot :)
